app/models.py
from . import db
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import UserMixin
from datetime import datetime
from . import login_manager

@login_manager.user_loader
def load_user(user_id):
  return User.query.get(int(user_id))

class User(UserMixin,db.Model):
    __tablename__ = 'users'

    id = db.Column(db.Integer,primary_key = True)
    username = db.Column(db.String(255),index = True)
    email = db.Column(db.String(255),unique = True,index = True)
    bio = db.Column(db.String(255))
    profile_pic_path = db.Column(db.String())
    pass_secure = db.Column(db.String(255))
    posts = db.relationship('Post', backref='user', lazy=True)
    comments = db.relationship('Comment', backref ='user', lazy=True)
    likes = db.relationship('Like', backref ='user', lazy=True)
    
    @property
    def password(self):
        raise AttributeError('You cannot read the password attribute')

    @password.setter
    def password(self, password):
        self.pass_secure = generate_password_hash(password)


    def verify_password(self,password):
        return check_password_hash(self.pass_secure,password)

    def __repr__(self):
        return f'User {self.username}'

class Post(db.Model):
     __tablename__ = 'posts'

     id = db.Column(db.Integer, primary_key=True)
     text = db.Column(db.Text, nullable=False)
     author = db.Column(db.Integer, db.ForeignKey('users.id'), nullable=False)
     comments = db.relationship('Comment', backref ='post', lazy=True)
     likes = db.relationship('Like', backref ='posts', lazy=True)


class Comment(db.Model):
     __tablename__ = 'comments'

     id = db.Column(db.Integer, primary_key=True)
     text = db.Column(db.String(200), nullable=False)
     author = db.Column(db.Integer, db.ForeignKey('users.id'), nullable=False)
     post_id = db.Column(db.Integer, db.ForeignKey('posts.id'), nullable=False)

class Like(db.Model):
     __tablename__ = 'likes'

     id = db.Column(db.Integer, primary_key=True)
     author = db.Column(db.Integer, db.ForeignKey('users.id'), nullable=False)
     post_id = db.Column(db.Integer, db.ForeignKey('posts.id'), nullable=False)


            

app/main/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, TextAreaField, SubmitField
from wtforms.validators import DataRequired

class UpdateProfile(FlaskForm):
    bio = TextAreaField('Tell us about you.',validators = [DataRequired()])
    submit = SubmitField('Submit')

app/__init__.py
from flask import Flask
from flask_bootstrap import Bootstrap
from config import config_options
from flask_sqlalchemy import SQLAlchemy
from flask_login import LoginManager

login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'

bootstrap = Bootstrap()
db = SQLAlchemy()

def create_app(config_name):
  app = Flask(__name__)

  # Creating the app configurations
  app.config.from_object(config_options[config_name])

  # initializing flask extenstions
  bootstrap.init_app(app)
  db.init_app(app)
  login_manager.init_app(app)

  # registering the blueprint
  from .main import main as main_blueprint
  app.register_blueprint(main_blueprint)
  from .auth import auth as auth_blueprint
  app.register_blueprint(auth_blueprint, url_prefix = '/auth')

  # setting config

  return app

app/main/__init__.py
from flask import Blueprint
main = Blueprint('main', __name__)
from . import views, error

app/main/views.py
from flask import render_template, request, redirect, url_for, abort,flash
from ..requests import get_blogQuotes
from . import main
from ..models import User, Post, Comment, Like
from flask_login import login_required, current_user
from datetime import datetime
from .. import db
from .forms import UpdateProfile

@main.route('/')
def index():
    '''
    '''
    blogQuote =get_blogQuotes()
    title = 'Welcome to My Blog'
    return render_template('index.html',title = title, blogQuote=blogQuote)
 
@main.route('/home')
@login_required
def home():
    posts = Post.query.all()
    return render_template("home.html" , user=current_user,posts=posts)

@main.route('/create-post', methods=['GET', 'POST'])
@login_required
def create_post():
    if request.method == 'POST':
        text = request.form.get('text')
        if not text:
            flash('Post cannot be empty', category='error')
        else:
            post = Post(text=text, author=current_user.id)
            db.session.add(post)
            db.session.commit()
            flash('Post created!', category='success')
            return redirect(url_for('main.home'))

    return render_template('create_post.html', user=current_user) 

@main.route('/delete-post/<id>')
@login_required
def delete_post(id):
    post = Post.query.filter_by(id=id).first()
    if not post:
        flash("Post does not exist.", category='error')
    elif current_user.id != post.id:
        flash("You do not have permission to delete this post.", category='error')
    else:
        db.session.delete(post)
        db.session.commit()
        flash('Post deleted', category='success')
    return redirect(url_for('main.home')) 


@main.route('/posts/<username>')
@login_required
def posts(username):
    user = User.query.filter_by(username=username).first()

    if not user:
        flash('No user with that username exists.', category='error')
        return redirect(url_for('main.home'))

    posts = user.posts
    return render_template('posts.html', user=current_user, posts=posts, username=username)

@main.route('/create-comment/<post_id>',methods=['POST'])
@login_required
def create_comment(post_id):
    text = request.form.get('text')

    if not text:
        flash('Comment cannot be empty')
    else: 
        post = Post.query.filter_by(id=post_id)
        if post:
            comment = Comment(text=text, author=current_user.id, post_id=post_id)
            db.session.add(comment)
            db.session.commit()
        else:
            flash('post does not exist.', category='error')    
    return redirect(url_for('main.home'))  

@main.route('/delete-comment/<comment_id>')
@login_required
def delete_comment(comment_id):
    comment = Comment.query.filter_by(id=comment_id).first()

    if not comment:
        flash("Comment does not exist.", category='error')
    elif current_user.id != comment.author and current_user.id != comment.post.author:
        flash("You do not have permission to delete this comment,", category='error')
    else:
        db.session.delete(comment)
        db.session.commit()
    return redirect(url_for('main.home'))   

@main.route('/like-post/<post_id>', methods=['GET'])
@login_required
def like(post_id):
    post = Post.query.filter_by(id=post_id)
    like = Like.query.filter_by(author=current_user.id, post_id=post_id).first()
    if not post:
        flash("Post does not exist", category='error')
    elif like:
        db.session.delete(like)
        db.session.commit()
    else:
        like = Like(author=current_user.id, post_id=post_id) 
        db.session.add(like)
        db.session.commit()   
    return redirect(url_for('main.home'))    


@main.route('/user/<uname>')
def profile(uname):
    user = User.query.filter_by(username = uname).first()

    if user is None:
        abort(404)

    return render_template("profile/profile.html", user = user)

@main.route('/user/<uname>/update',methods = ['GET','POST'])
@login_required
def update_profile(uname):
    user = User.query.filter_by(username = uname).first()
    if user is None:
        abort(404)

    form = UpdateProfile()

    if form.validate_on_submit():
        user.bio = form.bio.data

        db.session.add(user)
        db.session.commit()

        return redirect(url_for('.profile',uname=user.username))

    return render_template('profile/update.html',form =form)

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
    <script src="https://kit.fontawesome.com/139d77394a.js" crossorigin="anonymous"></script>
    {% block styles %}
    <link rel="stylesheet" href="{{url_for('static',filename='css/styles.css')}}">
    {% endblock %}
    <title>{% block title %}{% endblock %}</title>
</head>
<body style="background-image: url('https://getwallpapers.com/wallpaper/full/9/8/0/137871.jpg')">
  <nav class="navbar navbar-expand-lg navbar-dark bg-black"  role="navigation">
    <div class="container-fluid">
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbar">
         <span class="navbar-toggler-icon"></span>
      </button> 
       <div class="navbar-collapse collapse" id="navbar">
       <ul class="navbar-nav">
        <li><a class="nav-item nav-link" href="/">Quotes</a></li>
         <li><a class="nav-item nav-link" href="/home">Home</a></li>
       <ul class="nav navbar-nav navbar-right">
        {% if current_user.is_authenticated %}
        <li><a class="nav-item nav-link" href="{{url_for('main.profile',uname=current_user.username)}}">Profile</a></li>
        <li><a class="nav-item nav-link" href="{{url_for('auth.logout')}}">Sign out</a></li>
        {% else %}
        <li><a class="nav-item nav-link" href="{{url_for('auth.login')}}">Sign in</a></li>
        {%endif%}
       </ul>
     </div>
        </div>
  </nav>
  {% with messages = get_flashed_messages(with_categories=True) %} {% if messages %} {% for category, message in messages %} {% if category == 'error' %}
  <div class="alert alert-danger alert-dismissible fade show" role="alert">
    {{ message }}
    <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
    </div>
    {% else %} 
    <div class="alert alert-success alter-dismissible fade show" role="alert">
      {{ message }}
      <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
      </div>
      {% endif %} {% endfor %} {% endif %} {% endwith %} 

     <div class="container">{% block content %} {% endblock %}</div> 

    <!-- JavaScript Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>
    
</body>
</html>

app/templates/create_post.html
{% extends 'base.html' %} 
{% block title %}Home {% endblock %} 
{% block content %} 
<h1 align="center">Make a post</h1>

<form method="POST">
  <textarea name="text" id="text" class="form-control"></textarea>
  <br/>
  <div align="center">
    <button type="submit" class="btn btn-lg btn-primary">Post</button>
  </div>  
</form>
<br/>
<div align="center">
  <a href="/home"><button type="button" class="btn btn-lg btn-secondary">Back</button></a>
</div>  

{% endblock %} 

app/templates/fourOwfour.html
{% extends 'base.html' %}

{% block content %}
    <h1>WHOOPS we can't find that page</h1>
{% endblock %}

app/templates/home.html
{% extends 'posts_div.html' %}
{% block title %}Home{% endblock %} 

app/templates/index.html
{% extends 'base.html' %}
{% block title %} Welcome to my Blog {% endblock %}

{%block content%}

<div class="home">
  <div class="container">
    <div class="col-md-2"></div>
      <div class="col-md-8">
        <div>
          <h2 style="font-size: 80px; font-family: 'Lobster', cursive;  padding-top: 40px; text-align: center;"> Welcome to my Blog</h2>
          <br><br>
          <p>{{blogQuote.quote}}</p>
                
          <p class="text-right"><b>~ {{blogQuote.author}} ~</b> </p>

        </div>
        </div>
        <div class="col-md-2"></div>
    </div>

</div>
{%endblock%}

app/templates/posts.html
{% extends 'posts_div.html' %} 
{% block title %} {{username}}'s posts {% endblock %}
{% block header %} 
  {{username}}'s Posts
{% endblock %}
{% block footer %} 
<div align="center">
  <a href="/home"><button type="button" class="btn btn-primary btn-lg">Back</button></a>
</div>
{% endblock %}

app/templates/posts_div.html
{% extends 'base.html' %}
{% block title %} Home {% endblock %} 
{% block content %}
<h1 align="center">{% block header %}Posts{% endblock %}</h1> 
<div id="posts">
{% for post in posts %} 
<div class="card border-dark">
  <div class="card-header d-flex justify-content-between align-items-center">
    <a href='/posts/{{post.user.username}}'>{{post.user.username}}</a>
    <div>
      {{ post.likes|length}}
      {% if user.id in post.likes|map(attribute="author")|list %} 
      <a href="/like-post/{{post.id}}"><i class="fa-solid fa-thumbs-up"></i></a>
      {% else %}
      <a href="/like-post/{{post.id}}"><i class="fa-regular fa-thumbs-up"></i></a>
      {% endif %} 
      {% if user.id == post.author %} 
      <div class="btn-group">
        <button type="button" class="btn btn-sm btn-primary dropdown-toggle" data-bs-toggle="dropdown">
        </button>
        <ul class="dropdown-menu">
          <li><a href="/delete-post/{{post.id}}" class="dropdown-item">Delete</a></li>
        </ul>
      </div>
     {% endif %}
    </div>
    </div>
    <div class="card-body">
      <div class="card-text">{{post.text}}</div>
      <br/>
      <div class="collapse" id="comments-{{post.id}}">  
        <div class="card">
          <div class="card-body" id="comments-expanded-{{post.id}}">
            {% for comment in post.comments %} 
            <div clsss="d-flex justify-content-between align-items-center">
              <a href="/posts/{{comment.user.username}}">{{comment.user.username}}</a>:{{comment.text}}
              </div>
              <div>
                {% if user.id == comment.author or user.id == post.author %} 
              <div class="btn-group">
                <button type="button" class="btn btn-sm btn-primary dropdown-toggle" data-bs-toggle="dropdown">
                </button>
                <ul class="dropdown-menu">
                  <li><a href="/delete-comment/{{comment.id}}" class="dropdown-item">Delete</a></li>
                </ul>
              </div>
              {% endif %} 
            </div>
            {% endfor %}
            </div>
          </div>
        </div> 
       <p class="card-text"> 
        {% if post.comments|length > 0 %} 
        <a data-bs-toggle="collapse" href="#comments-{{post.id}}" role="button">
         <small>View {{post.comments|length}} Comments</small></a>
        {% else %} 
        <small class="text-muted">No Comments</small>
        {% endif %}
      </p> 
      <form class="input-group mb-3" method="POST" action="/create-comment/{{post.id}}" >
        <input type="text" id="text" name="text" class="form-control" placeholder="comment something!" />
        <button type="submit" class="btn btn-primary ">Comment</button>
      </form>
    </div>
  </div>
  <br>
{% endfor %} 
</div>
{% block footer %}
<div align="center">
  <a href="/create-post"><button type="button" class="btn btn-primary btn-lg">Create a Post</button></a>
 </div>
{% endblock %} 

{% endblock %} 

app/templates/profile/profile.html
{% extends 'base.html'%}

{% block content %}
<div class="container">
<div class="row">
<!-- displaying  Username-->
  <div class="col-md-4">
    <h3> {{user.username| capitalize}} </h3>

    <!--Displaying user bio-->
    {% if user.bio %}
      <p> {{user.bio}}</p>
    {%else%}
      <p> {{user.username| capitalize}} has no bio </p>
    {% endif %}
  </div>

  <!--Display profile photo-->
  <div class="col-md-4">

    {% if user.profile_pic_path %}
    <img src="{{url_for('static',filename=user.profile_pic_path)}}" alt="" class="img-thumbnail">
    {%else%}
    <p>No profile picture</p>
    {% endif %}

    {% if user == current_user %}
    <a href="{{url_for('main.update_profile',uname=user.username)}}">Edit profile</a>
{% endif %}
  </div>
</div>
</div>
{% endblock %} 

app/templates/profile/update.html
{% extends 'base.html' %}
{% import 'bootstrap/wtf.html' as wtf %}

{% block content %}
<div class="container">
  {{wtf.quick_form(form)}}
</div>
{% endblock %}